services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

    command: npm run dev -- --host 0.0.0.0